import { SubscriptionPlan } from '../types';

export const DUMMY_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-silver',
    name: 'Silver',
    headerIcon: 'Silver',
    controllers: '50-250 controllers',
    smsStorage: '(Includes: 100 SMS + 75MB storage)',
    priceAmount: 250,
    isInitialPlan: true,
    features: [
      { id: 'f1', text: '50-250 controllers', isIncluded: true },
      { id: 'f2', text: 'Single location', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: false },
      { id: 'f9', text: 'Customisable reporting', isIncluded: false },
      { id: 'f10', text: 'Muti-location management', isIncluded: false },
    ],
  },
  {
    id: 'plan-gold',
    name: 'Gold',
    headerIcon: 'Gold',
    tag: 'Your Current Plan',
    controllers: '250-500 controllers',
    smsStorage: '(Includes: 250 SMS + 150MB storage)',
    priceAmount: 550,
    isInitialPlan: true,
    features: [
      { id: 'f1', text: '250-500 controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: false },
      { id: 'f10', text: 'Muti-location management', isIncluded: false },
    ],
  },
  {
    id: 'plan-platinum',
    name: 'Platinum',
    headerIcon: 'Platinum',
    controllers: '500-1000 controllers',
    smsStorage: '(Includes: 500 SMS + 300MB storage)',
    priceAmount: 850,
    isInitialPlan: true,
    features: [
      { id: 'f1', text: '500-1000 controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: true },
      { id: 'f10', text: 'Muti-location management', isIncluded: false },
    ],
  },
  {
    id: 'plan-4',
    name: 'Plan 4',
    headerIcon: 'Plan 4',
    controllers: '1000-2000 controllers',
    smsStorage: '(Includes: 1000 SMS + 500MB storage)',
    priceAmount: 1200,
    isInitialPlan: false,
    features: [
      { id: 'f1', text: '1000-2000 controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: true },
      { id: 'f10', text: 'Muti-location management', isIncluded: false },
    ],
  },
  {
    id: 'plan-5',
    name: 'Plan 5',
    headerIcon: 'Plan 5',
    controllers: '2000-5000 controllers',
    smsStorage: '(Includes: 2000 SMS + 1GB storage)',
    priceAmount: 1800,
    isInitialPlan: false,
    features: [
      { id: 'f1', text: '2000-5000 controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: true },
      { id: 'f10', text: 'Muti-location management', isIncluded: true },
    ],
  },
  {
    id: 'plan-6',
    name: 'Plan 6',
    headerIcon: 'Plan 6',
    controllers: '5000+ controllers',
    smsStorage: '(Includes: 5000 SMS + 2GB storage)',
    priceAmount: 2500,
    isInitialPlan: false,
    features: [
      { id: 'f1', text: '5000+ controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: true },
      { id: 'f10', text: 'Muti-location management', isIncluded: true },
    ],
  },
  {
    id: 'plan-7',
    name: 'Plan 7',
    headerIcon: 'Plan 7',
    controllers: 'Custom controllers',
    smsStorage: '(Includes: Custom SMS + Custom storage)',
    priceAmount: 3000,
    isInitialPlan: false,
    features: [
      { id: 'f1', text: 'Custom controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: true },
      { id: 'f10', text: 'Muti-location management', isIncluded: true },
    ],
  },
  {
    id: 'plan-8',
    name: 'Plan 8',
    headerIcon: 'Plan 8',
    controllers: 'Custom controllers',
    smsStorage: '(Includes: Custom SMS + Custom storage)',
    priceAmount: 3500,
    isInitialPlan: false,
    features: [
      { id: 'f1', text: 'Custom controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: true },
      { id: 'f10', text: 'Muti-location management', isIncluded: true },
    ],
  },
  {
    id: 'plan-9',
    name: 'Plan 9',
    headerIcon: 'Plan 9',
    tag: 'Not Eligible',
    controllers: 'Custom controllers',
    smsStorage: '(Includes: Custom SMS + Custom storage)',
    priceAmount: 4000,
    isInitialPlan: false,
    features: [
      { id: 'f1', text: 'Custom controllers', isIncluded: true },
      { id: 'f2', text: 'Unlimited locations', isIncluded: true },
      { id: 'f3', text: 'Unlimited users', isIncluded: true },
      { id: 'f4', text: 'Mobile access', isIncluded: true },
      { id: 'f5', text: 'Mobile-enabled door entry', isIncluded: true },
      { id: 'f6', text: 'Remote door control', isIncluded: true },
      { id: 'f7', text: 'Real time activity log', isIncluded: true },
      { id: 'f8', text: 'Video intergration', isIncluded: true },
      { id: 'f9', text: 'Customisable reporting', isIncluded: true },
      { id: 'f10', text: 'Muti-location management', isIncluded: true },
    ],
  },
];
